os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "4.4.1"
jdk:
  - oraclejdk8
env:
  global:
    - GREENCODE_NODE_CACHE=1
    - PROFILE=dev
    - RUN_APP=1
    - PROTRACTOR=0
    - GREENCODE_TRAVIS=$TRAVIS_BUILD_DIR/travis
    - GREENCODE_INSTALL=$GREENCODE_TRAVIS/install
    - GREENCODE_SAMPLES=$GREENCODE_TRAVIS/samples
    - GREENCODE_SCRIPTS=$GREENCODE_TRAVIS/scripts
  matrix:
    - GREENCODE=app-default-from-scratch GREENCODE_NODE_CACHE=0
    - GREENCODE=app-gradle PROTRACTOR=1
    - GREENCODE=app-mysql PROFILE=prod PROTRACTOR=1
    - GREENCODE=app-psql-es-noi18n PROFILE=prod PROTRACTOR=1
    - GREENCODE=app-social-websocket PROTRACTOR=1
    - GREENCODE=app-cassandra
    - GREENCODE=app-microservice
    - GREENCODE=app-gateway
    - GREENCODE=app-hazelcast-cucumber
    - GREENCODE=app-mongodb
    - GREENCODE=app-oauth2
    - GREENCODE=app-jwt

before_install:
  - sudo /etc/init.d/postgresql stop
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - $GREENCODE_INSTALL/01-install-docker-compose.sh
  - $GREENCODE_INSTALL/02-install-greencode-stack.sh
  - $GREENCODE_INSTALL/03-checkVersion.sh
  - $GREENCODE_INSTALL/04-cache.sh
script:
  - $GREENCODE_SCRIPTS/01-generate-project.sh
  - $GREENCODE_SCRIPTS/02-generate-entities.sh
  - $GREENCODE_SCRIPTS/03-docker-compose.sh
  - $GREENCODE_SCRIPTS/04-tests.sh
  - $GREENCODE_SCRIPTS/05-run.sh
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c77e712c44b0a4914b7c
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
